version: "3.0"

services:
  hello-world:
    stdin_open: true
    environment: 
        - CHOKIDAR_USEPOLLING=true
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
